### ISSUE TITLE
GNU Social image missing

### ISSUE THREAD

**Issue by schiesbn** [chimo/gs-share#1]
I just give it a try and it works really great. It just seems like to GNU Social icon you you on your blog (http://chromic.org/blog/git-gogs-jekyll/) is missing here on github. Can you add it to the code?

**Comment by chimo** [comment]
Hi!
I've added an "example" folder that with a page that uses the logo.

The image is [here](https://github.com/chimo/gs-share/blob/master/examples/button-with-icon/images/gs-share.png)

The extra CSS required is in the <head> of the example page:
```css
    .js-gs-share {
        border: none;
        min-height: 32px;
        padding: 0;
        padding-left: 33px;
        background: url("images/gs-share.png") no-repeat left center;
    }
```

Let me know if that works for you
